name: Check Packages For Update
# Checks for packages updates:
# - Every 9AM UTC
# - On `./packages/*.sh` changes.

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"
  push:
    paths:
      - 'packages/*.sh'

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Check For Updates
        run: |
          ./scripts/check_updates.sh

      - name: Process Package Changes
        id: process_changes
        run: |
          if ! git diff --quiet packages/versions.ini; then
            VERSIONS="$(cat packages/versions.ini)"
            echo "Packages Updates Found!"
            echo "${VERSIONS}"

            COUNT=$(git diff packages/versions.ini | grep -E "^\+[A-Za-z0-9]" | grep -c "=" || true)

            echo "changed=true" >> $GITHUB_OUTPUT
            echo "count=${COUNT}" >> $GITHUB_OUTPUT
          else
            echo "No package updates."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.process_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: automated package updates"
          branch: auto-update-packages
          delete-branch: true
          title: "Automated Package Updates (${{ steps.process_changes.outputs.count }} updated)"
          body: |
            ### System Scan Report
            The automated package monitoring suite has caught version upgrades.

            #### Updated package signatures manifest:
            ```ini
            $(cat packages/versions.ini)
            ```
            *Review test validation check outputs prior to staging target mergers.*
          labels: |
            automated-pr
            dependencies
